package com.cs407_android.ormlab;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.cs407_android.ormlab.Guest;

import com.cs407_android.ormlab.GuestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig guestDaoConfig;

    private final GuestDao guestDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        guestDaoConfig = daoConfigMap.get(GuestDao.class).clone();
        guestDaoConfig.initIdentityScope(type);

        guestDao = new GuestDao(guestDaoConfig, this);

        registerDao(Guest.class, guestDao);
    }
    
    public void clear() {
        guestDaoConfig.getIdentityScope().clear();
    }

    public GuestDao getGuestDao() {
        return guestDao;
    }

}
